[package]
name = "saito-rust"
version = "0.1.0"
authors = ["Clayton Rabenda <clay@saito.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = { version = '0.20.2', features = ["rand", "serde"]  }
serde = { version = "1.0.125" }
rand = { version = '0.6.5' }
base58 = '0.1.0'
# rand_core = { version = '0.6.2' }