[package]
name = "saito_rust"
version = "0.1.0"
authors = [
    "Clayton Rabenda <clay@saito.tech>",
    "Stephen Peterkins <stephen@saito.tech>"
]
edition = "2018"
default-run = "saito_rust"

[[bin]]
name = "saito-spammer"
path = "src/bin/spammer.rs"

[dependencies]
base58 = "0.1.0"
bincode = "1.3"
chrono = "0.4"
clap = "3.0.0-beta.2"
hex = "0.4.3"
lazy_static = "1.4.0"
rand = "0.8.3"
rayon = "1.5"
rpassword = "5.0"
secp256k1 = { version = "0.20.2", features = ["global-context", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
sha2 = "0.9.5"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
warp = "0.3"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "add_block_benchmark"
harness = false

[features]
test-utilities = []
