[package]
name = "saito-rust"
version = "0.1.0"
authors = [
    "Clayton Rabenda <clay@saito.tech>",
    "Stephen Peterkins <stephen@saito.tech>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
secp256k1 = { version = "^0.20.2", features = ["rand", "serde"] }
sha2 = { version = "^0.9.4" }
rand = { version = "^0.6.5" }
base58 = { version = "^0.1.0" }
hex = { version = "^0.4.3" }
lazy_static = { version = "^1.4.0" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "saito_benchmark"
harness = false