[package]
name = "saito_rust"
version = "0.1.0"
authors = [
    "Clayton Rabenda <clay@saito.tech>",
    "Stephen Peterkins <stephen@saito.tech>"
]
edition = "2018"
default-run = "saito_rust"

[dependencies]
ahash = "0.7.4"
base58 = "0.1.0"
bigint = "4.4.3"
bincode = "1.3"
blake3 = { version = "0.3.8", features = ["rayon"] }
chrono = "0.4"
clap = "3.0.0-beta.2"
enum-variant-count-derive = { path = "enum-variant-count-derive" }
hex = "0.4.3"
jemalloc-ctl = "0.2.0"
jemallocator = "0.1.9"
lazy_static = "1.4.0"
merkle = "1.11.0"
rand = "0.8.4"
rayon = "1.5"
ring = "0.16.20"
rpassword = "5.0"
secp256k1 = { version = "0.20.3", features = ["global-context", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_with = "1.9.4"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
warp = "0.3"

[dev-dependencies]
criterion = "0.3"

[features]
test-utilities = []
