[package]
name = "saito-rust"
version = "0.1.0"
authors = ["Clayton Rabenda <clay@saito.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
